### PR TITLE
fix(tests): Corrected errors in unit tests

### PR DESCRIPTION
**Pull request by caitp**
inject() and module() can't be called whenever and wherever, which caused a
number of issues.

Use both of these methods in conjunction with beforeEach(), or some other
safe, pre-spec context.

Having an app name which loads after its controllers also poses a problem in
tests, because controllers/services/directives can be loaded before the app
module is ever instantiated (eg in app.js). Hence, I've renamed the main
module file to "app.js". This should always defeat the subdirectories in
ordering.

An alternative fix for this would be to simply load {%= name %}.js before
everything else in the karma configuration.

### CODE REVIEW

**Comment by caitp** [comment]
Whoops, broke 4-space indentation. My bad! Fixing..

**Comment by thebigredgeek** [comment]
Caitlin, can you be more specific regarding the inject and module usage, and the rules pertaining to them regarding testing?  I am trying to learn.  Also, what was your thought process in how you approached the problem?

**Comment by caitp** [comment]
Well, you can call inject() within specs, you need to make sure that module() is called before specs (or else it will throw). I don't fully understand the corner case, but it ends up not having an active spec, but still thinking it's in a spec, and then you get the reference error.

As for inject(), if you want to run it before a `spec/it()`, you need to wrap it in a before() or beforeEach(). Any tear-down stuff you need to do should happen in after()/afterEach(), but this mostly only matters for things like file handles and DB connections.

So the thought process in solving them is really just 1) look at the errors -> 2) look at the code -> 3) identify things which don't look right -> 4) replace them with things which are tried and true. At least, in this case anyway. I think I was getting more verbose error messages than you though, for whichever reason

**Comment by thebigredgeek** [comment]
@caitp , thats I really appreciate it!

**Pull request merged**
